[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
# family = "JetBrainsMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
# family = "JetBrainsMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
# family = "JetBrainsMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# family = "Hack Nerd Font Mono"
family = "BlexMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 0

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true

[window]
opacity = 0.95
blur = true

[window.padding]
x = 0
y = 0

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

